version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: shared.mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=35f929a94e3262632b238b99546b7216
    volumes:
      - /home/data/mongodb:/data/db
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true
